#!/bin/bash

echo "DISCONNECTING network cards"

ifconfig eth0 0.0.0.0 down
ifconfig eth1 0.0.0.0 down

echo "CREATE bridge"

brctl addbr nTap
brctl addif nTap eth0 eth1

ifconfig nTap down

echo "START BRIDGE"
ifconfig nTap up

echo "RECONNECT network cards"

ifconfig eth0 up
ifconfig eth1 up


excludeOwn="and not host $(hostname -I | sed "s/.$//g" | sed "s/ / and not host /g")"


tcpdump -q -i nTap not arp and not stp $excludeOwn
