#!/bin/bash

for ip in `hostname -I`; do
	if [ ${ip:0:7} == "169.254" ]; then
		continue
	fi
	echo "************************ SCAN OF $ip *************************"
	echo " "
	sudo nmap -sn -PR $ip/24 | grep report | sed 's/Nmap scan report for //g' | sort
done
