#!/bin/bash
echo "NETWORK TAPING FOR MAN IN THE MIDDLE ATTACKS"
read  -n 1 -p "Press any key to continue" mainmenuinput


echo "----> DISCONNECT NIC"
sudo ifconfig eth0 0.0.0.0 down
sudo ifconfig eth1 0.0.0.0 down


echo "----> CREATE BRIDGE nTap"
sudo brctl addbr nTap
sudo brctl addif nTap eth0 eth1
sudo ifconfig nTap down

echo "----> START BRIDGE nTap"
sudo ifconfig nTap up

echo "----> RECONNECT NIC"
sudo ifconfig eth0 up
sudo ifconfig eth1 up

echo "----> CONFIGURE BRIDGE using DHCP"
sudo dhclient nTap

echo "----> START filtered tcpdump"

filter="not arp and not stp and not host $(hostname -I | sed "s/.$//g" | sed "s/ / and not host /g") and not broadcast and not multicast"
sudo tcpdump -q -i nTap -ttttt $filter
