#!/bin/bash

filter="not stp and not host $(hostname -I | sed "s/.$//g" | sed "s/ / and not host /g")"
file="$(echo ~)/nTap-$(date +%y.%m.%d) $(date +%H-%M-%S).pcap"
command="sudo tcpdump -i nTap -w '$file' $filter"


echo "********** nTap - CAPTURE **********" 
echo "----> EXECUTED COMMAND: $command"
echo "----> TARGET FILE:      $file "
echo " "
echo " "
echo " "
echo " "
read  -n 1 -p "Press any key to continue" mainmenuinput

eval $command

