#!/bin/bash

FOLDER="$(echo ~)/out"
TARGET=$FOLDER/LatestUpdate.txt

mkdir -p $FOLDER


echo "****************************** CS UPDATE ******************************"


echo "Update $(date +%d.%m.%y) $(date +%H:%M:%S)" > $TARGET
echo "***************** APT-GET UPDATE *****************" >> $TARGET
sudo apt-get update >> $TARGET


echo " " >> $TARGET
echo " " >> $TARGET
echo " " >> $TARGET
echo " " >> $TARGET
echo "***************** APT-GET DIST-UPGRADE ***********" >> $TARGET
sudo apt-get -y dist-upgrade >> $TARGET

echo "COMPLETED"
