#!/bin/bash

echo SSIDs:
iwlist wlan0 scanning | sed -n -r 's/.*?ESSID:\"(.*?)\"/\  -> \1/p' | sort
echo 
echo ------------- CONFIG -----------------
read -p "SSID:    " wlanName
read -p "Password:" -s wlanPwd
echo
echo --------------------------------------


echo 
echo 
echo 
echo --- STOPPING WLAN SERVICE
sudo pkill wpa_supplicant
sudo ifconfig wlan0 down
sudo ifconfig wlan0 up




echo --- CONFIGURE
grep -q "auto wlan0" "/etc/network/interfaces" || echo "auto wlan0" >> /etc/network/interfaces
sed -i 's/iface wlan0 inet manual/iface wlan0 inet dhcp/' /etc/network/interfaces
echo country=GB > /etc/wpa_supplicant/wpa_supplicant.conf
echo ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev >> /etc/wpa_supplicant/wpa_supplicant.conf
echo update_config=1 >> /etc/wpa_supplicant/wpa_supplicant.conf


wpa_passphrase $wlanName $wlanPwd >> /etc/wpa_supplicant/wpa_supplicant.conf

sudo iwconfig wlan0 essid $wlanName 

echo --- STARTING WLAN SERVICE
sudo wpa_supplicant -B -Dnl80211 -i wlan0 -c /etc/wpa_supplicant/wpa_supplicant.conf

echo --- DHCP
sudo dhclient wlan0
